vanshg395/intl_phone_field

- lib/intl_phone_field.dart
New version flutter doesn't allow named parameter 'child' for the function showDialog
> No named parameter 'child' for showDialog function

- lib/intl_phone_field.dart
This is to handle feature requests [#43](https://github.com/vanshg395/intl_phone_field/issues/43).
A valid use case where the app is not available in all countries and the developer wants to restrict the list of countries to only the supported ones.
> Add ability to specify which countries to show in the dropdown

- lib/countries.dart
Côte d'Ivoire move from 8 to 10 digits phone number on January 31st 2021.
> Change Côte d'Ivoire phone max length

- lib/countries.dart
Portuguese numbers have 9 digits, not 1.
> fix Portugal max_length property

- lib/countries.dart
Argentina's phone numbers can be longer than 10 digits. In fact, any mobile number will be at least 11 digits, in the form of +54 911 33235445.
Area code can be 3 or 4 numbers long, and the rest of the number is usually 8 numbers long.
> Fix phone number max length for Argentina

- lib/countries.dart
The max length for Colombia was set at 0, which throws an assertion error in the base TextFormField.
> Fixed max number length for Colombia

- lib/intl_phone_field.dart
this PR has added the functionality to configure the dropdown icon position to be shown at the leading or trailing.
By default, it is `iconPosition: IconPosition.leading;`
Closes issue #80
> [feature]: icon position feature added

- lib/intl_phone_field.dart
In order to safely call setState() asynchronously, the "mounted" property of the State object (in this case, "_IntlPhoneFieldState"), needs to be validated. If mounted is not true, setState should not be called because it would result in the exception "Unhandled Exception: setState() called after dispose(), but did not call dispose method", since the widget was disposed and its state is no longer mounted.
> asynchronously call setState() in a safe way

- lib/intl_phone_field.dart
- pubspec.yaml
I found this adittion helpful, let me explain my issue
i encountered with this layout, the flags button was centered but looked offset cause the 0/10 label was making it go down a little
addding a custom padding helped me achieve this
```dart
IntlPhoneField(
flagsButtonPadding:
const EdgeInsets.only(top: 8, bottom: 30),
...
```
hope it gets added!
> Added property to set a custom padding on flag btn

- lib/countries.dart
As per https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Republic_of_Ireland, the minimum amount of numbers after the "0" or country code should be 7, with the max 9. If it needs to be the same for both, 9 would cover the max number of valid phone numbers.
This has been tested in my own app using my phone number, among others.
@all-contributors please add @cwwalsh for code
> Updated countries.dart with correct Ireland length

- example/pubspec.lock
- lib/intl_phone_field.dart
- pubspec.lock
I was using the package to do this:
But it ended to be zero-margined next to Flag button border.
- Added `dropDownMargin` property
- Wrapped FlagButtons with Container.
> Added dropDownMargin property

- lib/countries.dart
Sweden have a number range  between 7 to 13  https://en.wikipedia.org/wiki/Telephone_numbers_in_Sweden
> Update Sweden Phone number min to be 7 

- lib/countries.dart
Currently, Uruguay mobile numbers have a length of 9 digits. 
https://en.wikipedia.org/wiki/Telephone_numbers_in_Uruguay (see "Mobile Telephony")
> Update Uruguay phone number minimum value to 9

- lib/countries.dart
The international code of Ecuador is 593 and the digits that follow after this are 8 for landlines and 9 for mobiles.
Reference: https://es.wikipedia.org/wiki/N%C3%BAmeros_de_tel%C3%A9fono_en_Ecuador
> Update Ecuador Length

- lib/intl_phone_field.dart
initialCountryCode field did not work.
because widget.initialCountryCode is '+1' but item.code is 'US'. So I changed item.code to '+${item.dialCode}'. Because item.dialCode is '1' (for US example) and you need to add char '+' .
> Fixed initialCountryCode functionality

- lib/countries.dart
SG is 8 digits (e.g., 1234-5678)
> Corrected Singapore phone number length to 8

- lib/countries.dart
As per https://en.wikipedia.org/wiki/Telephone_numbers_in_Indonesia the minimum number of digits after the country code must be 10, with a maximum of 13.
@all-contributors please add @anggaraputrapratama for update mingLength code
> Updated countries.dart with correct Indonesia minLength

- lib/countries.dart
A Peruvian cell phone number consists of 9 digits instead of 11.
> Fix length for Peruvian phone number

- lib/countries.dart
Hello,
We are like USA and Canada. We have "dialCode" 829 - 809 and 849 + 7 digits like 000-0000. All phones number here are or +1809-000-0000 or +1829-000-0000 or +1849-000-0000
> Update countries.dart - For Dominican Republic

- lib/countries.dart
Without the leading zero, switzerland has 9 digits and not 12.
> Fix number of digits for Switzerland

- lib/countries.dart
fix based on wikipedia: https://en.wikipedia.org/wiki/Telephone_numbers_in_Italy#:~:text=The%20country%20code%20for%20calling,standard%20in%20most%20European%20countries.
> change italy country code to 39

- lib/countries.dart
As a Malaysian citizen and developer, I've made updates to the international phone field for **Malaysia**. 
In Malaysia, phone numbers have the following format: 
`Phone Key: (+60)`
phone number length of 9 digits following the phone key (`+60 123456789`). 
I've adjusted the
- `MinLength` from **11** to **9**
- `MaxLength` from **11** to **10**. 
This change aligns with the new phone number format provided by our updated phone number provider, which now includes numbers like `+60 1123456789.`
> Update the Length of Malaysia PhoneNumber

- lib/countries.dart
In Syria it's either to use the number with dialCode so number will be 9 digits
or use it without dialCode so number will be 10 digits
> fix Syrian Arab Republic phone number lenght
